"""empty message

Revision ID: a02c9037a857
Revises: fb1b292ab425
Create Date: 2024-05-30 01:23:15.060945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a02c9037a857'
down_revision = 'fb1b292ab425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_encounter', schema=None) as batch_op:
        batch_op.drop_constraint('fk_encountered_user_id', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_encounter', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_encountered_user_id', 'user', ['encountered_user_id'], ['id'])

    # ### end Alembic commands ###
